# coding: utf-8

"""
    BSUB.IO API

    REST API for batch processing compute-intensive workloads.  Submit jobs, upload data, and retrieve results through a simple API. Perfect for PDF processing, video transcoding, audio transcription, and more.  ## Authentication  All endpoints require Bearer token authentication using your API key:  ``` Authorization: Bearer <your-api-key> ```  Get your API key from the [Dashboard](/).  ## Job Lifecycle  1. **Create** a job with `POST /v1/jobs` - Returns job ID and upload token 2. **Upload** data with `POST /v1/upload/{jobId}` - Uses upload token 3. **Submit** for processing with `POST /v1/jobs/{jobId}/submit` 4. **Monitor** status with `GET /v1/jobs/{jobId}` 5. **Retrieve** output with `GET /v1/jobs/{jobId}/output`  ## Job States  - `created` - Job created, awaiting data upload - `loaded` - Data uploaded successfully - `pending` - Waiting in queue for a worker - `claimed` - Worker claimed the job - `preparing` - Worker preparing to process - `processing` - Processing started - `finished` - Processing completed successfully - `failed` - Processing failed with error 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsubio.models.processing_type import ProcessingType

class TestProcessingType(unittest.TestCase):
    """ProcessingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessingType:
        """Test ProcessingType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessingType`
        """
        model = ProcessingType()
        if include_optional:
            return ProcessingType(
                type = 'pdf/extract',
                name = 'PDF Text Extraction',
                description = 'Extract text from PDF documents',
                input = bsubio.models.processing_type_input.ProcessingType_input(
                    mime_in = ["application/pdf"], ),
                output = bsubio.models.processing_type_output.ProcessingType_output(
                    mime_out = ["text/plain"], 
                    ext = '.txt', 
                    display = 'text', ),
                example = bsubio.models.processing_type_example.ProcessingType_example(
                    cmd = 'bsubio submit pdf/extract document.pdf', 
                    desc = 'Extract text from a PDF file', )
            )
        else:
            return ProcessingType(
        )
        """

    def testProcessingType(self):
        """Test ProcessingType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
