# coding: utf-8

"""
    BSUB.IO API

    REST API for batch processing compute-intensive workloads.  Submit jobs, upload data, and retrieve results through a simple API. Perfect for PDF processing, video transcoding, audio transcription, and more.  ## Authentication  All endpoints require Bearer token authentication using your API key:  ``` Authorization: Bearer <your-api-key> ```  Get your API key from the [Dashboard](/).  ## Job Lifecycle  1. **Create** a job with `POST /v1/jobs` - Returns job ID and upload token 2. **Upload** data with `POST /v1/upload/{jobId}` - Uses upload token 3. **Submit** for processing with `POST /v1/jobs/{jobId}/submit` 4. **Monitor** status with `GET /v1/jobs/{jobId}` 5. **Retrieve** output with `GET /v1/jobs/{jobId}/output`  ## Job States  - `created` - Job created, awaiting data upload - `loaded` - Data uploaded successfully - `pending` - Waiting in queue for a worker - `claimed` - Worker claimed the job - `preparing` - Worker preparing to process - `processing` - Processing started - `finished` - Processing completed successfully - `failed` - Processing failed with error 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsubio.models.cancel_job200_response import CancelJob200Response

class TestCancelJob200Response(unittest.TestCase):
    """CancelJob200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CancelJob200Response:
        """Test CancelJob200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CancelJob200Response`
        """
        model = CancelJob200Response()
        if include_optional:
            return CancelJob200Response(
                success = True,
                message = 'Job cancelled'
            )
        else:
            return CancelJob200Response(
        )
        """

    def testCancelJob200Response(self):
        """Test CancelJob200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
