# coding: utf-8

"""
    BSUB.IO API

    REST API for batch processing compute-intensive workloads.  Submit jobs, upload data, and retrieve results through a simple API. Perfect for PDF processing, video transcoding, audio transcription, and more.  ## Authentication  All endpoints require Bearer token authentication using your API key:  ``` Authorization: Bearer <your-api-key> ```  Get your API key from the [Dashboard](/).  ## Job Lifecycle  1. **Create** a job with `POST /v1/jobs` - Returns job ID and upload token 2. **Upload** data with `POST /v1/upload/{jobId}` - Uses upload token 3. **Submit** for processing with `POST /v1/jobs/{jobId}/submit` 4. **Monitor** status with `GET /v1/jobs/{jobId}` 5. **Retrieve** output with `GET /v1/jobs/{jobId}/output`  ## Job States  - `created` - Job created, awaiting data upload - `loaded` - Data uploaded successfully - `pending` - Waiting in queue for a worker - `claimed` - Worker claimed the job - `preparing` - Worker preparing to process - `processing` - Processing started - `finished` - Processing completed successfully - `failed` - Processing failed with error 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsubio.models.create_job201_response import CreateJob201Response

class TestCreateJob201Response(unittest.TestCase):
    """CreateJob201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJob201Response:
        """Test CreateJob201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateJob201Response`
        """
        model = CreateJob201Response()
        if include_optional:
            return CreateJob201Response(
                success = True,
                data = bsubio.models.job.Job(
                    id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 
                    status = 'finished', 
                    type = 'pandoc_md', 
                    user_id = 'user123', 
                    upload_token = 'tok_abc123xyz789', 
                    data_size = 1048576, 
                    claimed_by = 'worker-01.bsub.io', 
                    error_code = 'ENOMEM', 
                    error_message = 'Out of memory while processing PDF', 
                    created_at = '2024-01-15T10:30Z', 
                    updated_at = '2024-01-15T10:35Z', 
                    claimed_at = '2024-01-15T10:31Z', 
                    finished_at = '2024-01-15T10:35Z', )
            )
        else:
            return CreateJob201Response(
        )
        """

    def testCreateJob201Response(self):
        """Test CreateJob201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
