# coding: utf-8

"""
    BSUB.IO API

    REST API for batch processing compute-intensive workloads.  Submit jobs, upload data, and retrieve results through a simple API. Perfect for PDF processing, video transcoding, audio transcription, and more.  ## Authentication  All endpoints require Bearer token authentication using your API key:  ``` Authorization: Bearer <your-api-key> ```  Get your API key from the [Dashboard](/).  ## Job Lifecycle  1. **Create** a job with `POST /v1/jobs` - Returns job ID and upload token 2. **Upload** data with `POST /v1/upload/{jobId}` - Uses upload token 3. **Submit** for processing with `POST /v1/jobs/{jobId}/submit` 4. **Monitor** status with `GET /v1/jobs/{jobId}` 5. **Retrieve** output with `GET /v1/jobs/{jobId}/output`  ## Job States  - `created` - Job created, awaiting data upload - `loaded` - Data uploaded successfully - `pending` - Waiting in queue for a worker - `claimed` - Worker claimed the job - `preparing` - Worker preparing to process - `processing` - Processing started - `finished` - Processing completed successfully - `failed` - Processing failed with error 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bsubio.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_job(self) -> None:
        """Test case for cancel_job

        Cancel a job
        """
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        Create a new job
        """
        pass

    def test_delete_job(self) -> None:
        """Test case for delete_job

        Delete a job
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get job details
        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List jobs
        """
        pass

    def test_submit_job(self) -> None:
        """Test case for submit_job

        Submit job for processing
        """
        pass

    def test_upload_job_data(self) -> None:
        """Test case for upload_job_data

        Upload data to a job
        """
        pass


if __name__ == '__main__':
    unittest.main()
